#!/usr/bin/env zsh

# **********************************
# This file gets generated by devctl
# Do not modify
# **********************************

export DEVCTL_HOME=$HOME/.devctl

# SDKS
export GOROOT=$DEVCTL_HOME/sdks/go/current

sdks=(
  go
  java
)

for sdk in ${sdks}
do
  echo "SDK: $sdk"
done

function add_sdk_to_path {
    sdk=$1
    sdkCurrentPath=$DEVCTL_HOME/sdks/$sdk/current
    export PATH=$PATH:$sdkCurrentPath
}

# PATH
export PATH=$PATH:$DEVCTL_HOME/

