#!/usr/bin/env bash
# Summary: List existing rbenv shims
# Usage: devctlenv shims [--short]

set -e
[ -n "$DEVCTL_DEBUG" ] && set -x

# Provide devctlenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "$DEVCTL_ROOT/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
